version: '3'
services:
  app:
    container_name: reservaksin-be
    build: .
    ports: 
      - 8080:8080 
    volumes:
      - api:/usr/src/app/
    restart: on-failure

volumes:
  api: